---
__nginx_default_packages:
  - "nginx-full"
  - "nginx"

__nginx_repositories_defaults:
  ppa_ondrej:
    enabled: false
    layout: debian
    packages:
      - "nginx-full"
      - "nginx"
    config:
      name: "ppa-ondrej-nginx"
      url: "https://ppa.launchpadcontent.net/ondrej/nginx/ubuntu"
      components:
        - "main"
      key_server: "keyserver.ubuntu.com"
      key_ids:
        - "0xB8DC7E53946656EFBCE4C1DD71DAEAAB4AD4CAB6"
      keyring: "/etc/apt/keyrings/ppa-ondrej-nginx.gpg"

  nginx_org:
    enabled: false
    layout: upstream
    packages:
      - "nginx"
    config:
      name: "nginx-org"
      url: "https://nginx.org/packages/ubuntu"
      suite: "{{ ansible_facts['distribution_release'] }}"
      components:
        - "nginx"
      key_url: "https://nginx.org/keys/nginx_signing.key"
      keyring: "/etc/apt/keyrings/nginx-org.gpg"

  nginx_org_mainline:
    enabled: false
    layout: upstream
    packages:
      - "nginx"
    config:
      name: "nginx-org-mainline"
      url: "https://nginx.org/packages/mainline/ubuntu"
      suite: "{{ ansible_facts['distribution_release'] }}"
      components:
        - "nginx"
      key_url: "https://nginx.org/keys/nginx_signing.key"
      keyring: "/etc/apt/keyrings/nginx-org-mainline.gpg"

__nginx_layouts_config:
  debian:
    runtime_user: "www-data"
    core_files:
      - nginx.conf
      - mime.types
      - fastcgi_params
      - proxy_params
      - scgi_params
      - uwsgi_params
    dirs:
      - conf.d
      - sites-available
      - sites-enabled
      - modules-available
      - modules-enabled
      - snippets

  upstream:
    runtime_user: "nginx"
    core_files:
      - nginx.conf
      - mime.types
      - fastcgi_params
      - scgi_params
      - uwsgi_params
    dirs:
      - conf.d

__nginx_dropins:
  proxy:
    description: "Global HTTP Proxy Settings"
    template: "generic"
    triggers:
      - "^nginx_proxy_"
    keys:
      - proxy_buffering
      - proxy_buffer_size
      - proxy_buffers
      - proxy_busy_buffers_size
      - proxy_cache_path
      - proxy_connect_timeout
      - proxy_headers_hash_bucket_size
      - proxy_headers_hash_max_size
      - proxy_max_temp_file_size
      - proxy_next_upstream
      - proxy_next_upstream_timeout
      - proxy_next_upstream_tries
      - proxy_read_timeout
      - proxy_send_timeout
  realip:
    description: "Global Real IP Settings"
    template: "realip"
    triggers:
      - "^nginx_real_ip_"

__nginx_mime_types_defaults:
  "text/html": "html htm shtml"
  "text/css": "css"
  "text/xml": "xml"
  "image/gif": "gif"
  "image/jpeg": "jpeg jpg"
  "application/javascript": "js"
  "application/atom+xml": "atom"
  "application/rss+xml": "rss"
  "text/mathml": "mml"
  "text/plain": "txt"
  "text/vnd.sun.j2me.app-descriptor": "jad"
  "text/vnd.wap.wml": "wml"
  "text/x-component": "htc"
  "image/avif": "avif"
  "image/png": "png"
  "image/svg+xml": "svg svgz"
  "image/tiff": "tif tiff"
  "image/vnd.wap.wbmp": "wbmp"
  "image/webp": "webp"
  "image/x-icon": "ico"
  "image/x-jng": "jng"
  "image/x-ms-bmp": "bmp"
  "font/woff": "woff"
  "font/woff2": "woff2"
  "application/java-archive": "jar war ear"
  "application/json": "json"
  "application/mac-binhex40": "hqx"
  "application/msword": "doc"
  "application/pdf": "pdf"
  "application/postscript": "ps eps ai"
  "application/rtf": "rtf"
  "application/vnd.apple.mpegurl": "m3u8"
  "application/vnd.google-earth.kml+xml": "kml"
  "application/vnd.google-earth.kmz": "kmz"
  "application/vnd.ms-excel": "xls"
  "application/vnd.ms-fontobject": "eot"
  "application/vnd.ms-powerpoint": "ppt"
  "application/vnd.oasis.opendocument.graphics": "odg"
  "application/vnd.oasis.opendocument.presentation": "odp"
  "application/vnd.oasis.opendocument.spreadsheet": "ods"
  "application/vnd.oasis.opendocument.text": "odt"
  "application/vnd.openxmlformats-officedocument.presentationml.presentation": "pptx"
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "xlsx"
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "docx"
  "application/vnd.wap.wmlc": "wmlc"
  "application/wasm": "wasm"
  "application/x-7z-compressed": "7z"
  "application/x-cocoa": "cco"
  "application/x-java-archive-diff": "jardiff"
  "application/x-java-jnlp-file": "jnlp"
  "application/x-makeself": "run"
  "application/x-perl": "pl pm"
  "application/x-pilot": "prc pdb"
  "application/x-rar-compressed": "rar"
  "application/x-redhat-package-manager": "rpm"
  "application/x-sea": "sea"
  "application/x-shockwave-flash": "swf"
  "application/x-stuffit": "sit"
  "application/x-tcl": "tcl tk"
  "application/x-x509-ca-cert": "der pem crt"
  "application/x-xpinstall": "xpi"
  "application/xhtml+xml": "xhtml"
  "application/xspf+xml": "xspf"
  "application/zip": "zip"
  "application/octet-stream": "bin exe dll deb dmg iso img msi msp msm"
  "audio/midi": "mid midi kar"
  "audio/mpeg": "mp3"
  "audio/ogg": "ogg"
  "audio/x-m4a": "m4a"
  "audio/x-realaudio": "ra"
  "video/3gpp": "3gpp 3gp"
  "video/mp2t": "ts"
  "video/mp4": "mp4"
  "video/mpeg": "mpeg mpg"
  "video/ogg": "ogv"
  "video/quicktime": "mov"
  "video/webm": "webm"
  "video/x-flv": "flv"
  "video/x-m4v": "m4v"
  "video/x-matroska": "mkv"
  "video/x-mng": "mng"
  "video/x-ms-asf": "asx asf"
  "video/x-ms-wmv": "wmv"
  "video/x-msvideo": "avi"
