---
galaxy_info:
  role_name: "haproxy"
  author: "Habr Team <servers@habr.team>, Vadim Rybalko <vadim@habr.team>"
  description: "Install HA-Proxy server"
  company: "Habr"
  issue_tracker_url: "https://git.habralab.com/tools/ansible-linuxhost/issues"
  license: "MIT"
  min_ansible_version: "2.16.0"
  platforms:
    - name: "Ubuntu"
      versions:
        - "xenial"
        - "bionic"
        - "focal"
        - "jammy"
        - "noble"
dependencies: []
