---
- name: Add NVM configuration to user profile
  ansible.builtin.blockinfile:
    path: "~{{ nvm_user }}/{{ nvm_profile }}"
    create: true
    mode: "0644"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: NVM"
    block: |
      export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
  become: true
  become_user: "{{ nvm_user }}"
