---
- name: Set NVM installation path
  ansible.builtin.set_fact:
    nvm_dir: "~{{ nvm_user }}/.nvm"

- name: Ensure NVM repository is cloned to the correct version
  ansible.builtin.git:
    repo: "{{ nvm_repo }}"
    dest: "{{ nvm_dir }}"
    version: "{{ nvm_version }}"
    depth: 1
    update: true
    accept_hostkey: true
    recursive: false
  become: true
  become_user: "{{ nvm_user }}"
