---
- name: Assert that nvm_users is defined and is a list
  ansible.builtin.assert:
    that:
      - nvm_users is defined
      - nvm_users | type_debug == 'list'
      - nvm_users | length > 0
    fail_msg: "Variable 'nvm_users' must be a list of dictionaries."
    quiet: true
  tags:
    - nvm

- name: Setup NVM for each user
  ansible.builtin.include_tasks:
    file: setup.yaml
    apply:
      tags:
        - nvm
  loop: "{{ nvm_users }}"
  loop_control:
    loop_var: current_nvm_user
    label: "{{ current_nvm_user.name }}"
  tags:
    - nvm
