---
- name: Install dependencies
  ansible.builtin.include_tasks: install.yaml
  tags:
    - nvm

- name: Configure NVM
  ansible.builtin.include_tasks: configure.yaml
  tags:
    - nvm

- name: Verify installation
  ansible.builtin.include_tasks: verify.yaml
  tags:
    - nvm
