---
- name: "Check if user exists: {{ current_nvm_user.name }}"
  ansible.builtin.getent:
    database: passwd
    key: "{{ current_nvm_user.name }}"
    fail_key: false

- name: "Fail if missing user: {{ current_nvm_user.name }}"
  ansible.builtin.assert:
    that:
      - getent_passwd is defined
      - getent_passwd.get(current_nvm_user.name) is not none
    fail_msg: >-
      The user '{{ current_nvm_user.name }}' does not exist on the target system.
      Please ensure the user is created before installing NVM.
    quiet: true

- name: "Clone NVM repository for user: {{ current_nvm_user.name }}"
  ansible.builtin.git:
    repo: "{{ nvm_repo }}"
    dest: "~{{ current_nvm_user.name }}/.nvm"
    version: "{{ current_nvm_user.version | default(nvm_version) }}"
    depth: 1
    update: true
    accept_hostkey: true
    recursive: false
  become: true
  become_user: "{{ current_nvm_user.name }}"
  diff: false

- name: "Add NVM configuration to profile for user: {{ current_nvm_user.name }}"
  ansible.builtin.blockinfile:
    path: "~{{ current_nvm_user.name }}/{{ current_nvm_user.profile | default(nvm_profile) }}"
    create: true
    mode: "0644"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: NVM"
    block: |
      export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
  become: true
  become_user: "{{ current_nvm_user.name }}"

- name: "Verify NVM version for user: {{ current_nvm_user.name }}"
  ansible.builtin.command:
    cmd: "bash -i -c 'nvm --version'"
  become: true
  become_user: "{{ current_nvm_user.name }}"
  register: nvm_check
  changed_when: false
  check_mode: false
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Print NVM version for user: {{ current_nvm_user.name }}"
  ansible.builtin.debug:
    msg: "NVM version for user {{ current_nvm_user.name }}: {{ nvm_check.stdout | default('Not installed yet (Check Mode)') }}"
