---
- name: Enable user lingering
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ item.name }}"
    creates: "/var/lib/systemd/linger/{{ item.name }}"
  loop: "{{ logind_linger_users }}"
  when: item.state | default('present') == 'present'
  loop_control:
    label: "{{ item.name }}"
  tags:
    - logind

- name: Disable user lingering
  ansible.builtin.command:
    cmd: "loginctl disable-linger {{ item.name }}"
    removes: "/var/lib/systemd/linger/{{ item.name }}"
  loop: "{{ logind_linger_users }}"
  when: item.state | default('present') == 'absent'
  loop_control:
    label: "{{ item.name }}"
  tags:
    - logind
