---
nginx_repo_manage: true

nginx_packages: []
nginx_remove_packages: []

nginx_repositories: {}

nginx_mime_types: {}

nginx_ssl_dhparam_size: 2048

nginx_working_dirs: []
nginx_extra_groups: []
nginx_cleanup_paths: []

nginx_include_sites_enabled: true
nginx_include_dirs: []
