---
nginx_repo_manage: true

nginx_packages: []
nginx_remove_packages: []

nginx_repositories: {}

nginx_mime_types: {}

nginx_ssl_dhparam_size: 2048

### LEGACY below!
nginx_working_owner: "www-data"
nginx_working_group: "www-data"

nginx_include_sites_enabled: true
nginx_include_dirs: []
