---
- name: Create MaxMind GeoIP configuration directory
  ansible.builtin.file:
    path: "{{ geoip_maxmind_config_path | dirname }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Create MaxMind GeoIP database directory
  ansible.builtin.file:
    path: "{{ geoip_maxmind_database_directory }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Write MaxMind GeoIP update configuration
  ansible.builtin.template:
    src: GeoIP.conf.j2
    dest: "{{ geoip_maxmind_config_path }}"
    owner: "{{ geoip_maxmind_config_owner }}"
    group: "{{ geoip_maxmind_config_group }}"
    mode: "{{ geoip_maxmind_config_mode }}"
  become: true
  no_log: "{{ geoip_maxmind_config_no_log }}"
