---
apt_repo_var_suite: "{{ apt_repo_config.suite | default(apt_repo_suite) }}"
apt_repo_var_components: "{{ apt_repo_config.components | default(apt_repo_components) }}"
apt_repo_var_is_flat: "{{ apt_repo_var_suite.endswith('/') }}"
apt_repo_var_keyring: "{{ apt_repo_config.keyring | default(apt_repo_keyring) }}"
apt_repo_var_key_active: >-
  {{
    (apt_repo_config.key_url | default(apt_repo_key_url) | length > 0) or
    (apt_repo_config.key_ids | default(apt_repo_key_ids) | length > 0)
  }}

apt_repo_var_arch_str: "arch={{ apt_repo_config.arch | default(apt_repo_arch) }}"
apt_repo_var_sign_str: "{{ 'signed-by=' ~ apt_repo_var_keyring if apt_repo_var_key_active | bool else '' }}"
apt_repo_var_opts: "{{ [apt_repo_var_arch_str, apt_repo_var_sign_str] | select | join(' ') }}"
apt_repo_var_comps_str: "{{ apt_repo_var_components | join(' ') if not apt_repo_var_is_flat | bool else '' }}"
