---
- name: "Create ipset service for legacy distributions"
  ansible.builtin.copy:
    src: "ipset.service"
    dest: "/lib/systemd/system/ipset.service"
    owner: root
    group: root
    mode: "0644"
  when:
    - netfilter_use_ipset | bool
    - ansible_facts['distribution_release'] not in netfilter_ipset_persistent_available_releases
  become: true
  notify:
    - Reload systemd
  tags:
    - netfilter
    - systemd

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers
  when:
    - netfilter_use_ipset | bool
    - ansible_facts['distribution_release'] not in netfilter_ipset_persistent_available_releases
  tags:
    - netfilter
    - systemd

- name: "Configure ipsets"
  ansible.builtin.template:
    src: "ipsets.j2"
    dest: "/etc/iptables/ipsets"
    owner: root
    group: root
    mode: "0644"
  when: netfilter_use_ipset | bool
  become: true
  notify:
    - Restart netfilter-persistent
    - Restart legacy ipset
  tags:
    - netfilter

- name: "Configure iptables"
  ansible.builtin.template:
    src: "rules.j2"
    dest: "/etc/iptables/rules.v{{ item }}"
    owner: root
    group: root
    mode: "0644"
  when: netfilter_use_iptables | bool
  become: true
  loop:
    - 4
    - 6
  notify:
    - Restart netfilter-persistent
  tags:
    - netfilter
