---
- name: "Install netfilter-persistent packages"
  ansible.builtin.import_tasks: install_netfilter_persistent.yml
  tags:
    - netfilter

- name: "Configure netfilter-persistent"
  ansible.builtin.import_tasks: configure_netfilter_persistent.yml
  when:
    - netfilter_use_ipset | bool or netfilter_use_iptables | bool
  tags:
    - netfilter
