---
- name: Converge runtime-bound npm packages
  ansible.builtin.include_tasks:
    file: npm_package.yml
  loop: "{{ _nodejs_environment.runtime.npm_packages }}"
  loop_control:
    loop_var: current_nodejs_npm_package
    label: "{{ current_nodejs_npm_package.name }}"
