---
- name: "Import GPG keys from direct URL | {{ apt_repo_config.name }}"
  ansible.builtin.apt_key:
    url: "{{ apt_repo_var_key_url }}"
    keyring: "{{ apt_repo_var_keyring }}"
    state: present
  when:
    - (apt_repo_config.state | default(apt_repo_state)) == 'present'
    - apt_repo_var_key_url | length > 0
  notify: Update apt cache

- name: "Import GPG keys from keyserver | {{ apt_repo_config.name }}"
  ansible.builtin.apt_key:
    id: "{{ key_item }}"
    keyserver: "{{ apt_repo_config.key_server | default(apt_repo_key_server) }}"
    keyring: "{{ apt_repo_var_keyring }}"
    state: present
  loop: "{{ [apt_repo_var_key_ids] | flatten }}"
  loop_control:
    loop_var: key_item
  when:
    - (apt_repo_config.state | default(apt_repo_state)) == 'present'
    - apt_repo_var_key_ids | length > 0
    - apt_repo_var_key_url | length == 0
  notify: Update apt cache

- name: "Configure repository (.list format) | {{ apt_repo_config.name }}"
  ansible.builtin.apt_repository:
    repo: "{{ apt_repo_var_repo_parts | select | join(' ') }}"
    state: "{{ apt_repo_config.state | default(apt_repo_state) }}"
    filename: "{{ apt_repo_config.name }}"
  vars:
    apt_repo_var_repo_parts:
      - "{{ type_item }}"
      - "{{ '[' ~ apt_repo_var_opts ~ ']' if apt_repo_var_opts | length > 0 else '' }}"
      - "{{ apt_repo_config.url }}"
      - "{{ apt_repo_var_suite }}"
      - "{{ apt_repo_var_comps_str }}"
  loop: "{{ apt_repo_config.types | default(apt_repo_types) }}"
  loop_control:
    loop_var: type_item
  notify: Update apt cache

- name: "Remove keyring file if repository is absent | {{ apt_repo_config.name }}"
  ansible.builtin.file:
    path: "{{ apt_repo_var_keyring }}"
    state: absent
  when: (apt_repo_config.state | default(apt_repo_state)) == 'absent'
  notify: Update apt cache
