---
netfilter_persistent_available_releases:
 - "xenial"
 - "bionic"
 - "focal"
 - "jammy"
 - "noble"
 - "resolute"

netfilter_iptables_persistent_available_releases:
 - "xenial"
 - "bionic"
 - "focal"
 - "jammy"
 - "noble"
 - "resolute"

netfilter_ipset_persistent_available_releases:
 - "focal"
 - "jammy"
 - "noble"
 - "resolute"
