---
galaxy_info:
  role_name: "nvm"
  author: "Habr Team <servers@habr.team>, Vadim Rybalko <vadim@habr.team>"
  description: "NodeJS Vertion Manager from git"
  company: "Habr"
  issue_tracker_url: "https://github.com/habralab/habr-ansible-collection/issues"
  license: "MIT"
  min_ansible_version: "2.15"
  platforms:
    - name: "Ubuntu"
      versions:
        - "focal"
        - "jammy"
        - "noble"
dependencies: []
