---
galaxy_info:
  role_name: "haproxy_sidecar"
  author: "Habr Team <servers@habr.team>"
  description: "HA-Proxy Sidecar instances provisioning via conf.d"
  company: "Habr"
  issue_tracker_url: "https://github.com/habralab/habr-ansible-collection/issues"
  license: "MIT"
  min_ansible_version: "2.16.0"
  platforms:
    - name: "Ubuntu"
      versions:
        - "xenial"
        - "bionic"
        - "focal"
        - "jammy"
        - "noble"
dependencies:
  - role: "habr.linuxhost.haproxy"
