---
_mariadb_config_file: /etc/mysql/mariadb.conf.d/90-ansible.cnf

_mariadb_config_common:
  server:
    sql-mode: >-
      STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    explicit-defaults-for-timestamp: true
    event-scheduler: true
    default-storage-engine: InnoDB
    character-set-server: utf8mb4
    collation-server: utf8mb4_unicode_ci
    init-connect: '""'

    bind-address: "127.0.0.1"
    max-connections: 200
    wait-timeout: 3600
    connect-timeout: 30
    open-files-limit: 32768

    long-query-time: 1
    skip-external-locking: null

    key-buffer-size: 16M
    sort-buffer-size: 2M
    thread-cache-size: 64
    query-cache-min-res-unit: 4K
    query-cache-limit: 1M
    max-allowed-packet: 64M
    max-heap-table-size: 32M
    tmp-table-size: 32M

    myisam-sort-buffer-size: 16M
    myisam-repair-threads: 1

    innodb-file-per-table: true
    innodb-buffer-pool-size: 128M
    innodb-log-file-size: 96M
    innodb-log-buffer-size: 16M
    innodb-flush-log-at-trx-commit: 1
    innodb-autoinc-lock-mode: 1
    innodb-flush-method: O_DIRECT

    query-cache-type: "OFF"
    query-cache-size: 0

    server-id: 1
    binlog-ignore-db:
      - information_schema
      - performance_schema
    replicate-ignore-db:
      - information_schema
      - performance_schema
    log-slave-updates: "OFF"
    log-bin: false
    relay-log: false
    auto-increment-offset: 1
    auto-increment-increment: 1
    expire-logs-days: 7
    sync-binlog: 1
    read-only: "OFF"
    binlog-format: false

  galera:
    wsrep-on: "OFF"
    wsrep-provider: none
    wsrep-cluster-name: MariaDB Galera Cluster
    wsrep-cluster-address: '""'
    wsrep-slave-threads: 1
