---
ssh_authorized_keys_catalog: {}
ssh_authorized_keys_groups: {}
ssh_authorized_keys_contract: {}
ssh_authorized_keys_users_base: {}
ssh_authorized_keys_users_overlay: {}
ssh_authorized_keys_manage_dir: true
