---
postgres_version: "18"

postgres_repository_manage: true
postgres_repository_name: pgdg
postgres_repository_url: https://apt.postgresql.org/pub/repos/apt
postgres_repository_suite: "{{ ansible_facts['distribution_release'] }}-pgdg"
postgres_repository_components:
  - main
postgres_repository_arch: >-
  {{ postgres_architecture_map.get(ansible_facts['architecture'], '') }}
postgres_repository_key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
postgres_repository_keyring: /etc/apt/keyrings/postgresql-pgdg.gpg

postgres_packages:
  - "postgresql-{{ postgres_version }}"
  - "postgresql-client-{{ postgres_version }}"

postgres_cluster_name: main
postgres_service_name: postgresql
postgres_service_enabled: true
postgres_service_state: started

postgres_config_manage: false
postgres_config_no_log: true
postgres_config: {}
postgres_config_dir: >-
  /etc/postgresql/{{ postgres_version }}/{{ postgres_cluster_name }}/conf.d
postgres_config_path: "{{ postgres_config_dir }}/90-ansible.conf"
postgres_config_stock_path: >-
  /etc/postgresql/{{ postgres_version }}/{{ postgres_cluster_name }}/postgresql.conf
postgres_data_dir: >-
  /var/lib/postgresql/{{ postgres_version }}/{{ postgres_cluster_name }}

postgres_hba_manage: false
postgres_hba_no_log: false
postgres_hba_rules: []
postgres_hba_stock_path: >-
  /etc/postgresql/{{ postgres_version }}/{{ postgres_cluster_name }}/pg_hba.conf
postgres_hba_include_dir: >-
  /etc/postgresql/{{ postgres_version }}/{{ postgres_cluster_name }}/pg_hba.conf.d
postgres_hba_path: "{{ postgres_hba_include_dir }}/90-ansible.conf"

postgres_health_check_enabled: true
postgres_health_host: 127.0.0.1
postgres_health_port: 5432
postgres_health_retries: 10
postgres_health_delay: 2
